# Generated by Django 3.1.3 on 2020-12-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersOsos', '0003_userlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
