# Generated by Django 3.1.3 on 2020-12-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentsOsos', '0002_auto_20201201_2151'),
        ('teachersOsos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_location', models.CharField(max_length=45, null=True)),
                ('class_term', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100, null=True)),
                ('course_type', models.CharField(choices=[('LABORATORY', 'Laboratory'), ('LECTURE', 'Lecture'), ('PROJECT', 'Project'), ('SEMINARY', 'Seminary'), ('PRACTICALS', 'Practicals')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.CharField(choices=[('2.0', '2.0'), ('3.0', '3.0'), ('3.5', '3.5'), ('4.0', '4.0'), ('4.5', '4.5'), ('5.0', '5.0'), ('5.5', '5.5')], max_length=10)),
                ('grade_type', models.CharField(choices=[('PARTIAL', 'Partial'), ('FINAL', 'Final')], max_length=10)),
                ('date_of_approval', models.DateField(null=True)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classesOsos.class')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsOsos.student')),
                ('teacher_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersOsos.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classesOsos.course'),
        ),
        migrations.AddField(
            model_name='class',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsOsos.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teachersOsos.teacher'),
        ),
    ]
