# Generated by Django 3.1.3 on 2020-12-05 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classesOsos', '0002_auto_20201205_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_id',
            new_name='clasS_id',
        ),
    ]
