# Generated by Django 3.1.3 on 2020-12-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classesOsos', '0003_auto_20201205_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='clasS_id',
            new_name='class_id',
        ),
        migrations.RenameField(
            model_name='grade',
            old_name='clasS',
            new_name='classs',
        ),
    ]
