# Generated by Django 3.1.3 on 2020-12-08 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classesOsos', '0005_auto_20201206_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='student',
        ),
    ]
