# Generated by Django 3.1.3 on 2020-12-08 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsOsos', '0004_studentlog'),
        ('classesOsos', '0006_remove_grade_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='studentsOsos.student'),
            preserve_default=False,
        ),
    ]
