# Generated by Django 3.1.4 on 2021-01-02 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentsOsos', '0006_student_user'),
        ('classesOsos', '0007_grade_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='student',
        ),
        migrations.CreateModel(
            name='ClassStudents',
            fields=[
                ('class_students_id', models.AutoField(primary_key=True, serialize=False)),
                ('classs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classesOsos.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentsOsos.student')),
            ],
        ),
    ]
