# Generated by Django 3.1.3 on 2020-11-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='testModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('status', models.CharField(max_length=250)),
                ('endDate', models.DateField()),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
