# Generated by Django 3.1.3 on 2020-12-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersOsos', '0001_initial'),
        ('mailboxOsos', '0001_initial'),
        ('studentsOsos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=13, null=True)),
                ('inauguration_date', models.DateField()),
                ('department_name', models.CharField(max_length=45)),
                ('field_of_study', models.CharField(max_length=45)),
                ('mail_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailboxOsos.mail')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usersOsos.user')),
            ],
        ),
        migrations.DeleteModel(
            name='testModel',
        ),
    ]
