# Generated by Django 3.1.3 on 2020-12-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentsOsos', '0003_auto_20201205_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
