# Generated by Django 3.1.4 on 2021-01-02 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsOsos', '0004_studentlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
    ]
