# Generated by Django 3.1.4 on 2021-01-02 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersOsos', '0004_auto_20201227_1806'),
        ('studentsOsos', '0005_remove_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default='Workata', on_delete=django.db.models.deletion.CASCADE, to='usersOsos.user'),
            preserve_default=False,
        ),
    ]
