# Generated by Django 3.1.3 on 2020-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersOsos', '0002_auto_20201205_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
