# Generated by Django 3.1.4 on 2021-01-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachersOsos', '0003_teacherlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
    ]
