# Generated by Django 3.1.3 on 2020-12-05 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsOsos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='user_id',
            new_name='user',
        ),
    ]
