# Generated by Django 3.1.4 on 2021-01-02 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminsOsos', '0002_auto_20201205_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
    ]
