# Generated by Django 3.1.3 on 2020-12-01 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('mail_id', models.CharField(max_length=70, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('message_title', models.CharField(max_length=45)),
                ('message_content', models.CharField(max_length=1000, null=True)),
                ('posting_date', models.DateField()),
                ('receiver_mail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='mailboxOsos.mail')),
                ('sender_mail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='mailboxOsos.mail')),
            ],
        ),
    ]
